// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9Hgu2qqTIDfSbkb7S6KHlj1puSgeznYw',
    appId: '1:648527491117:web:754a958e4dc6b7e801c8a4',
    messagingSenderId: '648527491117',
    projectId: 'taskmanagement-6f79c',
    authDomain: 'taskmanagement-6f79c.firebaseapp.com',
    storageBucket: 'taskmanagement-6f79c.firebasestorage.app',
    measurementId: 'G-WFW1L97HRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu9yJTBd6Oej5SdW0ju2Uv9RTYyVK56Mc',
    appId: '1:648527491117:android:b64c5e6fc364187d01c8a4',
    messagingSenderId: '648527491117',
    projectId: 'taskmanagement-6f79c',
    storageBucket: 'taskmanagement-6f79c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwn2VthFKnRt2Cres8iA4cqn0c74CNeD4',
    appId: '1:648527491117:ios:be51650a2749fb5e01c8a4',
    messagingSenderId: '648527491117',
    projectId: 'taskmanagement-6f79c',
    storageBucket: 'taskmanagement-6f79c.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwn2VthFKnRt2Cres8iA4cqn0c74CNeD4',
    appId: '1:648527491117:ios:be51650a2749fb5e01c8a4',
    messagingSenderId: '648527491117',
    projectId: 'taskmanagement-6f79c',
    storageBucket: 'taskmanagement-6f79c.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9Hgu2qqTIDfSbkb7S6KHlj1puSgeznYw',
    appId: '1:648527491117:web:796cd609a67d20f501c8a4',
    messagingSenderId: '648527491117',
    projectId: 'taskmanagement-6f79c',
    authDomain: 'taskmanagement-6f79c.firebaseapp.com',
    storageBucket: 'taskmanagement-6f79c.firebasestorage.app',
    measurementId: 'G-CQPEKX28MY',
  );
}

